spring:
  profiles:
    active: local   # 기본 실행 프로파일
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  jackson:
    time-zone: Asia/Seoul
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: limhyejinimagine@gmail.com
    password: gvjg ppgz fymo bgvw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: OFF          # SQL 로그 완전히 끄기
    org.hibernate.type: OFF         # 파라미터 바인딩 로그도 끄기
    org.hibernate.engine.jdbc.spi.SqlStatementLogger: OFF
    org.hibernate.orm.jdbc.bind: OFF   # (Hibernate 6.x 일 경우)
    com.imagine.card.card_application: INFO
    c.i.c.c.config.RoutingDataSource: WARN



