
# 통합테스트용: H2 + Flyway 끔 + Redis 락 비활성
spring:
  datasource:
    url: jdbc:h2:mem:carddb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: false

app:
  redis:
    lock:
      enabled: false
