spring:
  messages:
    basename: ValidationMessages
    encoding: UTF-8

  flyway:
    enabled: true
    baseline-on-migrate: true

  datasource:
    url: jdbc:mysql://localhost:3306/card_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: card_user
    password: card_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379    # Docker 포트 6379로 열었음
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jpa:
    hibernate:
      ddl-auto: none  # create(실행 시 매번 테이블 새로 생성) / update(테이블 자동 갱신  / validate(테이블 존재 여부만 검사)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # (선택) 시간대 통일
  jackson:
    time-zone: Asia/Seoul

aws:
  s3:
    bucket: card-application-storage  # 버킷 이름
    region: ap-northeast-2

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
