version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: card_pass
      MYSQL_DATABASE: card_db
    ports:
      - "3306:3306"
    volumes:
      - master_data:/var/lib/mysql          # 네임드 볼륨 (호스트 경로 X)
      - ./master_conf:/etc/mysql/conf.d     # Master 전용 설정 파일

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: card_pass
      MYSQL_DATABASE: card_db
    ports:
      - "3307:3306"
    depends_on:
      - mysql-master
    volumes:
      - slave_data:/var/lib/mysql           # 네임드 볼륨
      - ./slave_conf:/etc/mysql/conf.d      # Slave 전용 설정 파일

volumes:
  master_data:
  slave_data:
